### ISSUE TITLE
建议支持表前缀切换以及设置默认字符集为utf-8mb4

### ISSUE THREAD

**Issue by pedoc** [stulzq/Hangfire.MySql.Core#14]
RT，hangfire用到的表都默认没有任何前缀，建议通过Option可配置表前缀
另外，由于内置的sql初始化脚本建表默认的字符集为latin1会导致中文等Unicode字符集存储时sql报错

**Comment by LeviLv** [comment]
我也遇到这个问题，不知道作者还在不在维护这个项目

**Comment by pedoc** [comment]
@LeviLv 恩，又不想自己fork一个，我已经换另外一个库了。https://github.com/arnoldasgudas/Hangfire.MySqlStorage
这个也不错，不过需要1.1.2beta版才支持设置表前缀，其字符集编码问题依然存在，我提了issue

**Comment by stulzq** [comment]
编码和表前缀已解决
