### ISSUE TITLE
The Connectionstring was adding duplicate values. as a result of which the dictionary was not able to add duplicate key values in the below code snippet

### ISSUE THREAD

**Issue by konarpriyanku** [stulzq/Hangfire.MySql.Core#20]
The Connectionstring was adding duplicate values. as a result of which the dictionary was not able to add duplicate key values in the below code snippet

_connectionString.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries) .Select(x => x.Split(new[] { '=' }, StringSplitOptions.RemoveEmptyEntries)) .Select(x => new { Key = x[0].Trim(), Value = x.Length>1? x[1].Trim():"" }) .ToDictionary(x => x.Key, x => x.Value, StringComparer.OrdinalIgnoreCase);

**Comment by konarpriyanku** [comment]
pr for this #19

**Comment by stulzq** [comment]
Thanks
