### ISSUE TITLE
Fix to MySqlConnector 0.31.0 breaks Hangfire.MySql.Core

### ISSUE THREAD

**Issue by MiloszKrajewski** [stulzq/Hangfire.MySql.Core#3]
Hi,

New release of MySqlConnector 0.31.0 breaks Hangfire.MySql.Core. It throws some MySqlException exception every time you want schedule some jobs. The reason is this fix:
https://github.com/mysql-net/MySqlConnector/issues/389

Apparently, for new `Commands` the `Transaction` is no longer automatically set.

Thanks,

**Comment by stulzq** [comment]
Hi,
I already know the problem, thank you for reminding me，but now I do not have time to fix this problem.Please wait a few days,and now use the mysqlconnector old version to solve the problem

**Comment by cusanelly** [comment]
Hi stulzq.

I'm facing the same issue, but for v0.32.0.
However, I followed your recommendation and downgraded mysqlconnector to an older version.
Just to let you know about this issue.

Take care and Happy Holidays!

**Comment by stulzq** [comment]
Hi,

I've just solved this problem.A little change,What needs to be explained is this project code is base on Hangfire.MysqlStorage. I think some of the code is not well.I'll take the time to rewrite the code.If you check the code, you'll find that I just removed two lines of code, and that's the cancellation of the transaction.Why do I have to do this,because the original code is CRUD  execute once every time  the transaction is submitted,didn't make the transaction play a role。

**Comment by stulzq** [comment]
The nuget has updated the preview version .https://www.nuget.org/packages/Hangfire.MySql.Core/2.1.6-preview

**Comment by MiloszKrajewski** [comment]
I think you might be wrong.
Because `UseTransaction` calls some arbitrary `func` you don't know how many SQL statements are in this `func`. Which also means that if there are many statements in `func` and one of them fails the transaction won't be reverted and database will be left in corrupted state.

The option is pass `transaction` to this `func` and trace all the usages of it setting `comment.Transaction = transaction`.

**Comment by stulzq** [comment]
@MiloszKrajewski Yes,I was wrong,thank you for reminding me

**Comment by juan-arias** [comment]
Maybe an update on this issue?

**Comment by MiloszKrajewski** [comment]
@juan-arias my guess would be that as original package (https://github.com/arnoldasgudas/Hangfire.MySqlStorage) now supports .NET Core (.NET Standard 2.0 to be precise) this one will be/already is abandoned.
