### ISSUE TITLE
 The distributedlock table does not have a PK.

### ISSUE THREAD

**Issue by boost98** [stulzq/Hangfire.MySql.Core#33]
The distributedlock table does not have a PK.

It does not work in a Cluster-Mysql(Replication) environment.

https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html

**Comment by stulzq** [comment]
Thank you for your feedback. I will set the primary key for it.

**Comment by digithrone** [comment]
I've been playing with Percona XtraDb cluster and also ran on the PK issue. Currently I am using custom build but I will switch as soon as install.sql is fixed with PK.
