### ISSUE TITLE
 2.1.5 is not compatible with netcoreapp1.1

### ISSUE THREAD

**Issue by empitegayan** [stulzq/Hangfire.MySql.Core#4]
does this package not support netcoreapp1.1?
when i try to install nuget im getting this error
`Package Hangfire.MySql.Core 2.1.5 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Hangfire.MySql.Core 2.1.5 supports: netstandard2.0 (.NETStandard,Version=v2.0)`

**Comment by stulzq** [comment]
please，use 1.0
