### ISSUE TITLE
Infinite loop in ExpirationManager

### ISSUE THREAD

**Issue by configcat** [stulzq/Hangfire.MySql.Core#7]
Hello!

I found an infinite loop in the ExpirationManager.cs.
After debugging the package i found out that this code returns -1 if there are more than one statements in the query:
`removedCount = connection.Execute(
                                    String.Format(
                                        "select null from `{0}` where ExpireAt < @now; " +
                                        "delete from `{0}` where ExpireAt < @now limit @count;", table),
                                    new {now = DateTime.UtcNow, count = NumberOfRecordsInSinglePass});`

There is a check `if (removedCount > 0)` which is working fine with the removedCount=-1 case too (fortunately), but the do-while's `while (removedCount != 0);` causes an infinite loop without any delays.

Removing the `select null from `{0}` where ExpireAt < @now; ` from the connection.Execute solved the problem for me.
I also modified the exit point to `while (removedCount > 0);` just to be sure this could never cause an infinite loop again.

Cheers

**Comment by mattheworres** [comment]
@configcat please see the PR I've created. This solved the issue for me and I am running off of a temporary DLL I've compiled myself.

**Comment by mtschneiders** [comment]
@stulzq Any chance you could release a new nuget version with this fix?
